name: ClusterFuzzLite

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 0'

# Declare default permissions as read only.
permissions: read-all

jobs:
  cflite-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Run code-change fuzzing
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          mode: code-change
          fuzz-seconds: 600
        continue-on-error: true

  cflite-batch:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Run batch fuzzing
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          mode: batch
          fuzz-seconds: 1800
        continue-on-error: true
